### ISSUE TITLE
Malloc Panics with -O0 or crane_lift

### ISSUE THREAD

**Issue by eldesh** [jfecher/ante#174] opened 2023-12-20 16:42 UTC
In e38231f, compiling the following code at -O0:
```
size: Usz = 1
main () =
  _ = malloc size

main ()
```

Results in the compiler panicking and outputting the following error:
```
$ ante  -b bug.an
thread 'main' panicked at src/cranelift_backend/context.rs:197:13:
- inst0 (v1 = call fn0(v0)): arg 0 (v0) has type i8, expected i64

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
No errors occur with -O3.

**Comment by jfecher** [comment] 2023-12-20 16:51
This is a duplicate of #142. The code works as expected when using `malloc 1` directly.

**Comment by jfecher** [comment] 2023-12-20 16:52
This is a duplicate of https://github.com/jfecher/ante/issues/142. The code works as expected when using malloc 1 directly.

**Closed by jfecher** 2023-12-20 16:52 UTC
